export const SET_CURRENT_PAGE="SET_CURRENT_PAGE";
export const SET_PER_PAGE="SET_PER_PAGE";
export const ADD_TO_FAVOURITES="ADD_TO_FAVOURITES";
export const USE_CACHE="USE_CACHE";
export const FETCH_DATA_REQUEST="FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS="FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE="FETCH_DATA_FAILURE";
export const SET_FILTERED_DATA="SET_FILTERED_DATA";

